name: gtk_flutter
description: Get to know Firebase with Flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  # flutterfire_ui: ^0.3.4
  google_fonts: ^2.1.0
  material: ^1.0.0+2
  provider: ^6.0.2
  splashscreen: ^1.3.5
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.2.3
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.1
  timeago: ^3.2.2
  image_picker: ^0.8.4+1
  image_cropper: ^1.5.0
  rating_dialog: ^2.0.3
  rating: ^1.0.0-dev.1
  flutter_rating_bar: ^4.0.0
  firebase_storage: ^10.2.8
  getwidget: ^2.0.5
  favorite_button: ^0.0.4
  avatar_view: ^1.0.1
  http: ^0.13.4
  carousel_slider: ^4.0.0
  flutter_html: ^2.2.1
  form_builder_validators: ^8.1.0
  flutter_form_builder: ^7.1.1
  
  # flutter_bloc: ^6.0.6
  # equatable: ^1.2.5
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  firebase_storage_platform_interface: 4.0.14

flutter:
  uses-material-design: true
  assets: 
    - assets/
